locales:
  fit:
    name: Meänkieli Keyboards
    description: >-
      Mobile OS keyboards for the Meänkieli language from the Divvun group
      at UiT.
  en:
    name: Meänkieli Keyboards
    description: >-
      Mobile OS keyboards for the Meänkieli language from the Divvun group
      at UiT.
  nb:
    name: Meänkieli tastatur
    description: Mobiltastatur for Meänkieli fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
