locales:
  fit:
    name: Meänkieli-näppäimistöt
    description: >-
      Näppäimistöt Meänkielille UiT:n Divvun-ryhmästä ja Giellatekno-ryhmästä.
  en:
    name: Meänkieli Keyboards
    description: >-
      Keyboards for the Meänkieli language from the Divvun and Giellatekno groups
      at UiT.
  nb:
    name: Meänkieli tastatur
    description: Tastatur for Meänkieli fra Divvun-gruppa ved UiT.
author: 'The Divvun Group and the Giellatekno Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2024 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
